#!/usr/bin/env bash
# scripts/lib/render-project-docs.sh
#
# BL-109 SLICE-S3 / BL-101 landing — the PARAMETERIZED generator for the two
# script-rendered (Class A1) project docs: CLAUDE.md and PROJECT_INTAKE.md.
#
# WHY THIS EXISTS. init.sh renders CLAUDE.md and PROJECT_INTAKE.md from templates
# with project-specific substitutions. The Currency System's A1 three-way merge
# (design v1.1 §2-L2, Class A1) needs to re-render the OLD template (at the
# framework pin) and the NEW template (at HEAD) with the SAME recovered vars, then
# `git merge-file` render-then (base) / render-now (theirs) / user-file-now (ours)
# into a candidate. The v1 design merged TEMPLATE legs directly — that injects
# `__PROJECT_NAME__`-class placeholders into the candidate (review-r1 B3b, the I3
# nightmare). Rendering the legs through THIS generator (BL-101's actual mechanism)
# kills that: both legs are fully substituted, so no placeholder can reach a merge.
#
# BYTE-IDENTITY CONTRACT (the hook-templates.sh precedent). init.sh calls these
# functions at birth. They MUST reproduce init.sh's former inline render byte-for-
# byte on identical inputs — every sed expression, the conditional organizational
# append, the intake pre-fill sed, and the tooling-summary append are preserved
# verbatim. tests/test-plan-staging.sh pins this against an inline reference
# render; tests/test-currency-birth-stamp.sh pins it end-to-end (the captured
# render-base output sha must equal the scaffolded file's sha).
#
# bash-3.2 safe: no associative arrays, no `[[ -v ]]`, no `((x++))` under set -e.
# Pure renderers — the only writes are to the caller-named <out> file (+ sed's
# <out>.bak, which is removed). NO globals are read EXCEPT where a birth-only
# code path (the tooling summary's resolver output) is explicitly passed in.

# ── CLAUDE.md (A1) ───────────────────────────────────────────────────────────
# soif_render_claude_md <template> <out> \
#     <project_name> <description> <platform> <track> <language> \
#     <test_interval> <deployment>
#   Byte-identical to init.sh's former generate_claude_md render body (the sed
#   substitution + the conditional organizational Branch-Protection append). The
#   render-base capture stays at the init.sh call site (a birth-only concern).
soif_render_claude_md() {
  local tmpl="$1" out="$2" name="$3" desc="$4" platform="$5" track="$6" \
        language="$7" test_interval="$8" deployment="$9"
  sed -e "s|__PROJECT_NAME__|$name|g" \
      -e "s|__PROJECT_DESCRIPTION__|$desc|g" \
      -e "s|__PLATFORM__|$platform|g" \
      -e "s|__TRACK__|$track|g" \
      -e "s|__LANGUAGE__|$language|g" \
      -e "s|__TEST_INTERVAL__|$test_interval|g" \
      "$tmpl" > "$out"

  # Add compliance note for organizational deployments (verbatim from init.sh).
  if [ "$deployment" = "organizational" ]; then
    cat >> "$out" << 'COMPEOF'

### Branch Protection (Organizational Deployments)
Branch protection with required reviewers is recommended for organizational deployments and will be required when compliance modules are available. Until then, the Orchestrator creates and merges their own PRs with phase gate review at milestones. When branch protection is enabled, PRs require an independent reviewer before merge — this provides per-change code review that strengthens the governance audit trail.
COMPEOF
  fi
}

# ── PROJECT_INTAKE.md tooling summary (A1, birth-only append) ────────────────
# soif_append_intake_tooling_summary <resolver_output> <out> \
#     <os_type> <platform> <language> <track>
#   Byte-identical to init.sh's former append_intake_tooling_summary, with the
#   hardcoded `PROJECT_INTAKE.md` target and the four global reads made explicit
#   parameters. Birth-only: the plan-time render CANNOT recover <resolver_output>
#   (it is runtime tool-resolution state, not template-derived), so plan never
#   calls this — the user's existing tooling summary is preserved through the
#   three-way merge as ours-only trailing content.
soif_append_intake_tooling_summary() {
  local resolver_output="$1" out="$2" os_type="$3" platform="$4" language="$5" track="$6"

  cat >> "$out" << 'TOOLHDR'

---

## Tooling Configuration

> Auto-generated by init.sh. Full machine-readable config: `.claude/tool-preferences.json`

TOOLHDR

  # Resolved for
  echo "**Resolved for:** $os_type / $platform / $language / $track track" >> "$out"
  echo "" >> "$out"

  # Installed table
  local installed_count
  installed_count=$(echo "$resolver_output" | jq '.already_installed | length')
  if [ "$installed_count" -gt 0 ]; then
    echo "### Installed" >> "$out"
    echo "| Tool | Category | Version |" >> "$out"
    echo "|---|---|---|" >> "$out"
    echo "$resolver_output" | jq -r '.already_installed[] | "| \(.name) | \(.category) | \(.version) |"' >> "$out"
    echo "" >> "$out"
  fi

  # Manual setup table
  local manual_count
  manual_count=$(echo "$resolver_output" | jq '.manual_install | length')
  if [ "$manual_count" -gt 0 ]; then
    echo "### Manual Setup Required" >> "$out"
    echo "| Tool | Category | Instructions |" >> "$out"
    echo "|---|---|---|" >> "$out"
    echo "$resolver_output" | jq -r '.manual_install[] | "| \(.name) | \(.category) | \(.instructions) |"' >> "$out"
    echo "" >> "$out"
  fi

  # Deferred table
  local deferred_count
  deferred_count=$(echo "$resolver_output" | jq '.deferred | length')
  if [ "$deferred_count" -gt 0 ]; then
    echo "### Deferred (Phase 3+)" >> "$out"
    echo "| Tool | Phase | Category |" >> "$out"
    echo "|---|---|---|" >> "$out"
    echo "$resolver_output" | jq -r '.deferred[] | "| \(.name) | \(.phase) | \(.category) |"' >> "$out"
    echo "" >> "$out"
  fi
}

# ── PROJECT_INTAKE.md (A1) ───────────────────────────────────────────────────
# soif_render_project_intake <template> <out> \
#     <project_name> <description> <track> <platform> <deployment> <date> \
#     [resolver_output] [os_type] [language]
#   Byte-identical to init.sh's former inline PROJECT_INTAKE render path: cp
#   template → Section-1 pre-fill sed (with the __DATE__ substitution) → optional
#   tooling-summary append. <resolver_output> is birth-only; omit it (plan) and
#   only the template+sed structural render is produced. <os_type>/<language>
#   are only consulted when <resolver_output> is present (the tooling summary's
#   "Resolved for" line).
soif_render_project_intake() {
  local tmpl="$1" out="$2" name="$3" desc="$4" track="$5" platform="$6" \
        deployment="$7" date="$8" resolver_output="${9:-}" os_type="${10:-}" language="${11:-}"

  # Copy intake template
  cp "$tmpl" "$out"

  # Pre-fill Section 1 with init data so user doesn't enter it twice
  local platform_module="None"
  case "$platform" in
    web) platform_module="SOI-PM-WEB" ;;
    desktop) platform_module="SOI-PM-DESKTOP" ;;
    mobile) platform_module="SOI-PM-MOBILE" ;;
    mcp_server) platform_module="SOI-PM-MCP" ;;
  esac
  local track_display
  track_display="$(echo "${track:0:1}" | tr '[:lower:]' '[:upper:]')${track:1}"
  local deployment_display
  deployment_display="$(echo "${deployment:0:1}" | tr '[:lower:]' '[:upper:]')${deployment:1}"

  sed -i.bak \
    -e "s~| \*\*Project name\*\* | |~| **Project name** | $name |~" \
    -e "s~| \*\*One-sentence description\*\* | _What does this do, in plain language?_ |~| **One-sentence description** | $desc |~" \
    -e "s~| \*\*Project track\*\* | Light / Standard / Full .*~| **Project track** | $track_display |~" \
    -e "s~| \*\*Platform type\*\* | Web / Desktop / Mobile / CLI / Other: .*~| **Platform type** | $platform |~" \
    -e "s~| \*\*Platform Module\*\* | SOI-PM-WEB / SOI-PM-DESKTOP / SOI-PM-MOBILE / None .*~| **Platform Module** | $platform_module |~" \
    -e "s~| \*\*Is this a personal project or organizational deployment?\*\* | Personal / Organizational |~| **Is this a personal project or organizational deployment?** | $deployment_display |~" \
    -e "s~__DATE__~$date~g" \
    "$out"
  rm -f "$out.bak"

  # Append tooling configuration summary (birth-only — needs resolver output)
  if [ -n "$resolver_output" ]; then
    soif_append_intake_tooling_summary "$resolver_output" "$out" "$os_type" "$platform" "$language" "$track"
  fi
}
